apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservice-app
data:
  SPRING_PROFILES_ACTIVE: "prod"
  AUTH_DB_URL: "jdbc:postgresql://postgres-service:5432/auth_db"
  USER_DB_URL: "jdbc:postgresql://postgres-service:5432/userservice_db"
  ORDER_DB_URL: "jdbc:postgresql://postgres-service:5432/order_db"
  AUTHENTICATION_SERVICE_URI: "http://auth-service:8082"
  USER_SERVICE_URI: "http://user-service:8080"
  ORDER_SERVICE_URI: "http://order-service:8084"
  PAYMENT_SERVICE_URI: "http://payment-service:8088"
  SPRING_DATA_REDIS_HOST: "redis-service"
