apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservice-app
data:
  SPRING_PROFILES_ACTIVE: "prod"
  AUTH_DB_URL: "jdbc:postgresql://postgres-service:5432/auth_db"
  USER_DB_URL: "jdbc:postgresql://postgres-service:5432/userservice_db"
  ORDER_DB_URL: "jdbc:postgresql://postgres-service:5432/order_db"
  USER_SERVICE_URL: "http://user-service:8080"
